ARG GO_VERSION
FROM golang:$GO_VERSION
RUN \
  apt-get update && \
  apt-get install -y gcc-s390x-linux-gnu g++-s390x-linux-gnu

ENV CGO_ENABLED=1
ENV CC=s390x-linux-gnu-gcc
ENV CXX=s390x-linux-gnu-g++
ENV GOOS=linux
ENV GOARCH=s390x

